# Generated by Django 3.2.3 on 2021-11-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('username', models.CharField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('pickup', models.CharField(blank=True, max_length=300)),
                ('message', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CurierBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('pickup_location', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
