# Generated by Django 3.2.3 on 2021-09-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurierBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('pickup_location', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('start_time', models.TimeField(auto_now_add=True, null=True)),
                ('end_time', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='carbooking',
            old_name='phone',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='carbooking',
            name='image',
        ),
        migrations.AddField(
            model_name='carbooking',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
