# Generated by Django 3.2.3 on 2021-09-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210911_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='subject',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
