# Generated by Django 3.2.3 on 2021-09-12 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_carbooking_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbooking',
            old_name='description',
            new_name='message',
        ),
    ]
