# Generated by Django 3.2.3 on 2021-09-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_rename_description_carbooking_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbooking',
            old_name='name',
            new_name='username',
        ),
    ]
