# Generated by Django 3.2.3 on 2021-09-12 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_rename_name_carbooking_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carbooking',
            old_name='pickup_location',
            new_name='pickup',
        ),
    ]
