# Generated by Django 3.2.3 on 2021-10-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_rename_pickup_location_carbooking_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
