# Generated by Django 3.2.3 on 2021-10-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_carbooking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbooking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
