# Generated by Django 3.1.5 on 2021-03-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210309_1202'),
        ('user', '0002_auto_20210310_0501'),
    ]

    operations = [
    ]
