# Generated by Django 3.1.5 on 2021-03-15 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merge_20210314_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
    ]
